// netlify/functions/simon.js
// Baseline Simo backend: stable outputs for chat + HTML preview.
// NOTE: For real ChatGPT-level intelligence, wire this to OpenAI Responses API later.
// This baseline is about: "no blank page, no broken preview, predictable behavior".

let lastHTML = ""; // best-effort memory while function stays warm

function json(statusCode, obj) {
  return {
    statusCode,
    headers: {
      "Content-Type": "application/json; charset=utf-8",
      "Cache-Control": "no-store"
    },
    body: JSON.stringify(obj)
  };
}

function isBuildRequest(t){
  return /\b(build|make|create)\b/i.test(t) && /\b(landing page|website|page|app)\b/i.test(t);
}

function baseLandingHTML(topic){
  const safeTopic = (topic || "your idea").replace(/[<>]/g,"");
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>${safeTopic}</title>
<style>
  :root{color-scheme:light;}
  body{font-family:system-ui,-apple-system,Segoe UI,Roboto,Helvetica,Arial;margin:0;color:#0b1020;background:#f6f8ff;}
  header{padding:64px 20px;background:linear-gradient(135deg,#2a66ff,#6b2aff);color:white;}
  .wrap{max-width:980px;margin:0 auto;}
  h1{font-size:44px;line-height:1.05;margin:0 0 12px;}
  p{margin:0;opacity:.92;font-size:18px}
  .cta{margin-top:18px;display:inline-block;padding:12px 16px;border-radius:14px;background:#0b1020;color:#fff;text-decoration:none;font-weight:700}
  section{padding:26px 20px}
  .grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}
  @media(max-width:800px){.grid{grid-template-columns:1fr}}
  .card{background:#fff;border:1px solid rgba(10,20,40,.12);border-radius:18px;padding:16px}
  .card b{display:block;margin-bottom:6px}
  footer{padding:26px 20px;color:rgba(10,20,40,.65)}
</style>
</head>
<body>
<header>
  <div class="wrap">
    <h1 id="headline">Build ${safeTopic} faster.</h1>
    <p id="subhead">A clean, conversion-ready starting point — ready to customize.</p>
    <a class="cta" href="#start" id="cta">Get Started</a>
  </div>
</header>

<section id="start">
  <div class="wrap">
    <div class="grid">
      <div class="card"><b>Clear sections</b>Hero, features, and CTA built in.</div>
      <div class="card"><b>Mobile-ready</b>Responsive layout that adapts.</div>
      <div class="card"><b>Easy edits</b>Update headline, CTA, pricing, FAQ.</div>
    </div>
  </div>
</section>

<footer>
  <div class="wrap">Generated by Simo.</div>
</footer>
</body>
</html>`;
}

function applyEdit(html, input){
  if (!html) return "";
  const t = input.trim();

  // headline: ...
  const m1 = t.match(/^headline:\s*(.+)$/i);
  if (m1) {
    const val = m1[1].replace(/[<>]/g,"");
    return html.replace(/(<h1[^>]*id="headline"[^>]*>)([\s\S]*?)(<\/h1>)/i, `$1${val}$3`);
  }

  // cta: ...
  const m2 = t.match(/^cta:\s*(.+)$/i);
  if (m2) {
    const val = m2[1].replace(/[<>]/g,"");
    return html.replace(/(<a[^>]*id="cta"[^>]*>)([\s\S]*?)(<\/a>)/i, `$1${val}$3`);
  }

  // add faq
  if (/^add faq$/i.test(t) && !/id="faq"/i.test(html)) {
    const faq = `
<section id="faq">
  <div class="wrap">
    <h2>FAQ</h2>
    <div class="grid">
      <div class="card"><b>How fast can I launch?</b>In one afternoon with a few edits.</div>
      <div class="card"><b>Can I change the copy?</b>Yes — headline, CTA, and sections are easy.</div>
      <div class="card"><b>Is it mobile friendly?</b>Yes — responsive by default.</div>
    </div>
  </div>
</section>`;
    return html.replace(/<\/footer>/i, `</footer>${faq}`);
  }

  // remove faq
  if (/^remove faq$/i.test(t)) {
    return html.replace(/<section id="faq">[\s\S]*?<\/section>/i, "");
  }

  return html;
}

exports.handler = async (event) => {
  if (event.httpMethod !== "POST") {
    return json(405, { ok:false, error:"Use POST" });
  }

  let data = {};
  try { data = JSON.parse(event.body || "{}"); } catch {}

  const input = String(data.input || "").trim();
  if (!input) return json(200, { ok:true, text:"Tell me what you want to build.", html:"" });

  // Build request creates HTML
  if (isBuildRequest(input)) {
    lastHTML = baseLandingHTML(input.replace(/\b(build|make|create)\b/i,"").trim());
    return json(200, {
      ok: true,
      text: "Done. I updated the preview on the right.\n\nTry edits like:\n- headline: …\n- cta: …\n- add faq / remove faq",
      html: lastHTML
    });
  }

  // If there's existing HTML, apply edits
  if (lastHTML) {
    const updated = applyEdit(lastHTML, input);
    if (updated && updated !== lastHTML) {
      lastHTML = updated;
      return json(200, { ok:true, text:"Done. Updated the preview.", html:lastHTML });
    }
  }

  // Normal chat fallback (no HTML change)
  return json(200, {
    ok: true,
    text: lastHTML
      ? "Got it. If you want changes, try: headline: … | cta: … | add faq | remove faq"
      : "Ask me to build something first (example: “build a landing page for a fitness coach”).",
    html: ""
  });
};
