// netlify/functions/simon.js
// Offline deterministic builder (no OpenAI, no external APIs).
// Always returns JSON: { ok, text, html? }

function json(statusCode, obj) {
  return {
    statusCode,
    headers: {
      "Content-Type": "application/json; charset=utf-8",
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Headers": "Content-Type",
      "Access-Control-Allow-Methods": "POST, OPTIONS",
    },
    body: JSON.stringify(obj),
  };
}

function normalize(s){ return String(s || "").trim(); }

function escapeHtml(s){
  return String(s || "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

function baseTemplate(opts){
  const headline = escapeHtml(opts.headline || "Build Faster. Look Better.");
  const sub = escapeHtml(opts.sub || "A clean, modern landing page generated by Simo.");
  const cta = escapeHtml(opts.cta || "Get Started");
  const price = escapeHtml(opts.price || "29");
  const showFaq = !!opts.faq;
  const showPricing = !!opts.pricing;
  const showTestimonials = !!opts.testimonials;

  // markers allow safe edits
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>${headline}</title>
<style>
  :root{ --bg:#0b1020; --card:rgba(255,255,255,.06); --line:rgba(255,255,255,.12); --text:#eaf0ff; --muted:#a9b6d3; --btn:#2a66ff; }
  *{box-sizing:border-box} body{margin:0;font:16px/1.5 system-ui;background:radial-gradient(900px 600px at 20% 10%, rgba(42,102,255,.25), transparent 60%), var(--bg); color:var(--text);}
  .wrap{max-width:1100px;margin:0 auto;padding:56px 18px;}
  .hero{display:grid;grid-template-columns:1.2fr .8fr;gap:18px;align-items:center;}
  @media(max-width:900px){.hero{grid-template-columns:1fr}}
  .card{background:var(--card);border:1px solid var(--line);border-radius:18px;padding:18px;box-shadow:0 12px 28px rgba(0,0,0,.35);}
  h1{font-size:44px;line-height:1.05;margin:0 0 12px}
  p{color:var(--muted);margin:0 0 16px}
  .row{display:flex;gap:10px;flex-wrap:wrap;align-items:center}
  .btn{display:inline-block;background:linear-gradient(180deg, var(--btn), #1f4dd6); color:white; text-decoration:none; padding:12px 16px;border-radius:14px;border:1px solid rgba(42,102,255,.6);font-weight:700}
  .ghost{display:inline-block;color:var(--text);text-decoration:none;padding:12px 16px;border-radius:14px;border:1px solid var(--line);background:rgba(0,0,0,.15)}
  .grid3{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:14px}
  @media(max-width:900px){.grid3{grid-template-columns:1fr}}
  .k{font-weight:800}
  .section{margin-top:18px}
  .tag{display:inline-block;padding:6px 10px;border-radius:999px;border:1px solid var(--line);color:var(--muted);font-size:13px}
  .price{font-size:38px;font-weight:900}
  .small{font-size:13px;color:var(--muted)}
  ul{margin:10px 0 0 18px;color:var(--muted)}
</style>
</head>
<body>
  <!-- SIMO_MARKER:headline --> 
  <!-- SIMO_MARKER:cta -->
  <!-- SIMO_MARKER:price -->
  <!-- SIMO_MARKER:faq:${showFaq} -->
  <!-- SIMO_MARKER:pricing:${showPricing} -->
  <!-- SIMO_MARKER:testimonials:${showTestimonials} -->

  <div class="wrap">
    <div class="hero">
      <div class="card">
        <span class="tag">Simo Builder Demo</span>
        <h1 id="simo_headline">${headline}</h1>
        <p id="simo_sub">${sub}</p>
        <div class="row">
          <a class="btn" id="simo_cta" href="#">${cta}</a>
          <a class="ghost" href="#pricing">See pricing</a>
        </div>
        <div class="grid3 section">
          <div class="card"><div class="k">Fast</div><div class="small">Clean sections + modern layout.</div></div>
          <div class="card"><div class="k">Editable</div><div class="small">Use “headline: …”, “add faq”, etc.</div></div>
          <div class="card"><div class="k">Deployable</div><div class="small">Works as a standalone HTML file.</div></div>
        </div>
      </div>

      <div class="card" id="pricing">
        <div class="k">Starter</div>
        <div class="price">$<span id="simo_price">${price}</span><span class="small">/mo</span></div>
        <ul>
          <li>Landing page template</li>
          <li>CTA + hero + features</li>
          <li>Edits supported</li>
        </ul>
      </div>
    </div>

    ${showTestimonials ? `
    <div class="section card" id="testimonials">
      <div class="k">Testimonials</div>
      <p>“This looks insanely professional.” — Client A</p>
      <p>“Fast, clean, and easy to customize.” — Client B</p>
    </div>` : ""}

    ${showFaq ? `
    <div class="section card" id="faq">
      <div class="k">FAQ</div>
      <p><strong>How do I edit this?</strong><br/>Type commands like <em>headline:</em>, <em>cta:</em>, <em>price:</em>, <em>add faq</em>.</p>
      <p><strong>Is this production-ready?</strong><br/>It’s a solid starting point — customize as needed.</p>
    </div>` : ""}

    <div class="section card">
      <div class="k">Next</div>
      <p>Ask Simo to build something else or edit this one.</p>
    </div>
  </div>
</body>
</html>`;
}

function parseCommand(input){
  const s = normalize(input);
  const low = s.toLowerCase();

  if (/^headline\s*:/.test(low)) return { type:"headline", value: s.split(":").slice(1).join(":").trim() };
  if (/^cta\s*:/.test(low)) return { type:"cta", value: s.split(":").slice(1).join(":").trim() };
  if (/^price\s*:/.test(low)) return { type:"price", value: s.split(":").slice(1).join(":").trim().replace(/[^\d]/g,"") };

  if (/^add\s+faq/.test(low)) return { type:"toggle", key:"faq", on:true };
  if (/^remove\s+faq/.test(low)) return { type:"toggle", key:"faq", on:false };

  if (/^add\s+pricing/.test(low)) return { type:"toggle", key:"pricing", on:true };
  if (/^remove\s+pricing/.test(low)) return { type:"toggle", key:"pricing", on:false };

  if (/^add\s+testimonials/.test(low)) return { type:"toggle", key:"testimonials", on:true };
  if (/^remove\s+testimonials/.test(low)) return { type:"toggle", key:"testimonials", on:false };

  if (/^continue\b/.test(low)) return { type:"continue" };

  return { type:"build" };
}

function readMarkerBool(html, key){
  const re = new RegExp(`SIMO_MARKER:${key}:(true|false)`, "i");
  const m = String(html || "").match(re);
  return m ? (m[1].toLowerCase() === "true") : false;
}

function applyEdit(html, cmd){
  let out = String(html || "");
  if (!out.trim()) return out;

  if (cmd.type === "headline" && cmd.value){
    out = out.replace(/(<h1[^>]*id="simo_headline"[^>]*>)([\s\S]*?)(<\/h1>)/i, `$1${escapeHtml(cmd.value)}$3`);
    out = out.replace(/<title>[\s\S]*?<\/title>/i, `<title>${escapeHtml(cmd.value)}</title>`);
    return out;
  }
  if (cmd.type === "cta" && cmd.value){
    out = out.replace(/(<a[^>]*id="simo_cta"[^>]*>)([\s\S]*?)(<\/a>)/i, `$1${escapeHtml(cmd.value)}$3`);
    return out;
  }
  if (cmd.type === "price" && cmd.value){
    out = out.replace(/(<span[^>]*id="simo_price"[^>]*>)([\s\S]*?)(<\/span>)/i, `$1${escapeHtml(cmd.value)}$3`);
    return out;
  }
  if (cmd.type === "toggle"){
    const faq = (cmd.key === "faq") ? cmd.on : readMarkerBool(out, "faq");
    const pricing = (cmd.key === "pricing") ? cmd.on : readMarkerBool(out, "pricing");
    const testimonials = (cmd.key === "testimonials") ? cmd.on : readMarkerBool(out, "testimonials");

    // rebuild from extracted visible fields for safety
    const headline = (out.match(/id="simo_headline"[^>]*>([\s\S]*?)<\/h1>/i)?.[1] || "Build Faster. Look Better.").replace(/<[^>]+>/g,"");
    const cta = (out.match(/id="simo_cta"[^>]*>([\s\S]*?)<\/a>/i)?.[1] || "Get Started").replace(/<[^>]+>/g,"");
    const price = (out.match(/id="simo_price"[^>]*>([\s\S]*?)<\/span>/i)?.[1] || "29").replace(/<[^>]+>/g,"");

    return baseTemplate({ headline, cta, price, faq, pricing, testimonials, sub:"A clean, modern landing page generated by Simo." });
  }

  return out;
}

exports.handler = async (event) => {
  if (event.httpMethod === "OPTIONS") return json(200, { ok:true });
  if (event.httpMethod !== "POST") return json(405, { ok:false, error:"Use POST" });

  let body = {};
  try{ body = JSON.parse(event.body || "{}"); }catch{ body = {}; }

  const mode = normalize(body.mode || "build");
  const input = normalize(body.input || "");
  const current = String(body.current_html || "");

  const cmd = parseCommand(input);

  // BUILD: if no current html or explicit build request
  if (mode === "build" || cmd.type === "build" || !current.trim()){
    // light personalization from prompt keywords (no external calls)
    let headline = "Build Faster. Look Better.";
    let sub = "A clean, modern landing page generated by Simo.";
    if (/fitness|coach|gym|workout/i.test(input)){ headline = "Get Fit Without Guesswork"; sub = "A fitness coaching page you can edit instantly."; }
    if (/restaurant|pizza|coffee/i.test(input)){ headline = "Your Next Favorite Bite"; sub = "Restaurant landing page template — fast and clean."; }
    if (/app|saas|startup/i.test(input)){ headline = "Launch Your SaaS Cleanly"; sub = "A simple product page with editable sections."; }

    const html = baseTemplate({ headline, sub, cta:"Get Started", price:"29", faq:false, pricing:true, testimonials:false });
    return json(200, {
      ok:true,
      text:"Done. I updated the preview on the right.\n\nEdit commands:\n- headline: …\n- cta: …\n- price: 29\n- add faq / remove faq\n- add testimonials / remove testimonials",
      html
    });
  }

  // EDIT
  const edited = applyEdit(current, cmd);
  if (edited === current){
    return json(200, { ok:true, text:"I didn’t change anything. Try: headline: … | cta: … | price: 29 | add faq", html: current });
  }
  return json(200, { ok:true, text:"Done. Updated.", html: edited });
};
